<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CMS.ServiceManager-6229c3c5-2f55-4633-9d63-e45e88939dcb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CMS.Application\CMS.Application.csproj" />
    <ProjectReference Include="..\CMS.Infrastructure\CMS.Infrastructure.csproj" />
    <ProjectReference Include="..\CMS.Shared\CMS.Shared.csproj" />
  </ItemGroup>
</Project>
